global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.163.com:465'  # 网易邮箱SMTP服务器地址
  smtp_from: 'iamhuchenyu@163.com'    # 发件人邮箱
  smtp_auth_username: 'iamhuchenyu@163.com'   # 邮箱账号
  smtp_auth_password: '******'  # 授权码
  smtp_require_tls: false              # SSL加密

route:
  group_by: ['alertname', 'service']
  group_wait: 30s                     # 初始告警等待时间
  group_interval: 5m                  # 同组告警发送间隔
  repeat_interval: 3h                 # 重复告警间隔
  receiver: 'default-email'           # 默认接收人

receivers:
- name: 'default-email'
  email_configs:
  - to: 'iamhuchenyu@163.com'         # 收件人
    send_resolved: true               # 发送恢复通知
