# prometheus.yml
global:
  evaluation_interval: 15s  # 每15秒评估一次规则
  scrape_interval: 15s      # 默认抓取间隔为15秒

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['120.76.42.201:8081']

  - job_name: 'flask-app'
    static_configs:
      - targets: ['myapp:5000']
    metrics_path: /metrics

rule_files:
  - "/etc/prometheus/rules/*.yml"
